/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PL;

import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class PL_MENU extends javax.swing.JFrame {

    /**
     * Creates new form PL_MENU
     */
    public PL_MENU() {
        initComponents();
        if(PL_DANGNHAP.getTaiKhoan.tk.equals("admin")){
            jQltk.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jQltk = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuKH = new javax.swing.JMenuItem();
        jMenuMH = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("TÀI KHOẢN");

        jQltk.setText("QUẢN LÍ TÀI KHOẢN");
        jQltk.setEnabled(false);
        jQltk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQltkActionPerformed(evt);
            }
        });
        jMenu1.add(jQltk);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("QUẢN LÝ");

        jMenuKH.setText("KHÁCH HÀNG");
        jMenuKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuKHActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuKH);

        jMenuMH.setText("MẶT HÀNG");
        jMenuMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMHActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuMH);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jQltkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQltkActionPerformed
        // TODO add your handling code here:
        PL_QLTK ql = new PL_QLTK();
        ql.setLocationRelativeTo(null);
        ql.setVisible(true);
        ql.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jQltkActionPerformed

    private void jMenuKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuKHActionPerformed
        // TODO add your handling code here:
        PL_KhachHang kh = new PL_KhachHang();
        kh.setLocationRelativeTo(null);
        kh.setVisible(true);
        kh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuKHActionPerformed

    private void jMenuMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMHActionPerformed
        // TODO add your handling code here: 
        PL_MatHang x = new PL_MatHang();
        x.setLocationRelativeTo(null);
        x.setVisible(true);
        x.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenuMHActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PL_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PL_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PL_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PL_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PL_MENU().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuKH;
    private javax.swing.JMenuItem jMenuMH;
    private javax.swing.JMenuItem jQltk;
    // End of variables declaration//GEN-END:variables
}
